# Generated by Django 4.2.13 on 2024-07-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_doctor_address_alter_doctor_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='balance',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Balance'),
        ),
    ]
