# Generated by Django 4.2.13 on 2024-07-21 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_patient_address_alter_patient_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visittime',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.patient', verbose_name='Patient'),
        ),
    ]
