# Generated by Django 5.0.6 on 2024-07-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_speciality'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Speciality',
        ),
        migrations.AlterField(
            model_name='doctorinfo',
            name='speciality',
            field=models.CharField(choices=[('General', 'General'), ('Cardiology', 'Cardiology'), ('Dermatology', 'Dermatology'), ('Emergency Medicine', 'Emergency Medicine'), ('Endocrinology', 'Endocrinology'), ('Gastroenterology', 'Gastroenterology'), ('Neurology', 'Neurology'), ('Oncology', 'Oncology'), ('Pediatrics', 'Pediatrics'), ('Psychiatry', 'Psychiatry')], max_length=200),
        ),
    ]
