# Generated by Django 5.0.6 on 2024-07-09 20:57

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_delete_speciality_alter_doctorinfo_speciality'),
        ('users', '0004_alter_patientinfo_national_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField(choices=[(datetime.time(15, 0), '3:00 PM'), (datetime.time(15, 30), '3:30 PM'), (datetime.time(16, 0), '4:00 PM'), (datetime.time(16, 30), '4:30 PM'), (datetime.time(17, 0), '5:00 PM'), (datetime.time(17, 30), '5:30 PM'), (datetime.time(18, 0), '6:00 PM'), (datetime.time(18, 30), '6:30 PM'), (datetime.time(19, 0), '7:00 PM'), (datetime.time(19, 30), '7:30 PM'), (datetime.time(20, 0), '8:00 PM'), (datetime.time(20, 30), '8:30 PM')])),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.doctorinfo')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patientinfo')),
            ],
        ),
    ]
