# Generated by Django 5.0.6 on 2024-07-09 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_visittime'),
        ('users', '0004_alter_patientinfo_national_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visittime',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.patientinfo'),
        ),
    ]
