# Generated by Django 5.0.6 on 2024-07-09 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_visittime_patient'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='visittime',
            unique_together={('doctor', 'date', 'time')},
        ),
    ]
