# Generated by Django 4.2 on 2024-07-11 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0006_alter_visittime_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(max_length=500)),
                (
                    "score",
                    models.FloatField(
                        choices=[
                            (0, 0),
                            (0.5, 0.5),
                            (1, 1),
                            (1.5, 1.5),
                            (2, 2),
                            (2.5, 2.5),
                            (3, 3),
                            (3.5, 3.5),
                            (4, 4),
                            (4.5, 4.5),
                            (5, 5),
                        ]
                    ),
                ),
                (
                    "visit_time",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booking.visittime",
                    ),
                ),
            ],
        ),
    ]
